"""Type stubs for llvm_builder_py Python bindings."""

from typing import List, Callable, Optional
from enum import IntEnum

# Enums
class RuntimeType(IntEnum):
    unknown: int
    boolean: int
    int8: int
    int16: int
    int32: int
    int64: int
    uint8: int
    uint16: int
    uint32: int
    uint64: int
    float32: int
    float64: int
    pointer_struct: int
    pointer_array: int

class SymbolType(IntEnum):
    unknown: int
    custom_struct: int
    function: int

# Type system classes
class MemberFieldEntry:
    def __init__(self) -> None: ...
    def __init__(self, name: str, type: TypeInfo) -> None: ...
    def __init__(self, name: str, type: TypeInfo, is_readonly: bool) -> None: ...
    def name(self) -> str: ...
    def type(self) -> TypeInfo: ...
    def is_readonly(self) -> bool: ...
    def is_valid(self) -> bool: ...

class FieldEntry:
    def idx(self) -> int: ...
    def offset(self) -> int: ...
    def name(self) -> str: ...
    def type(self) -> TypeInfo: ...
    def is_readonly(self) -> bool: ...
    @staticmethod
    def null() -> FieldEntry: ...

class TypeInfo:
    def __init__(self) -> None: ...
    # Type queries
    def is_valid(self) -> bool: ...
    def is_void(self) -> bool: ...
    def is_boolean(self) -> bool: ...
    def is_integer(self) -> bool: ...
    def is_pointer(self) -> bool: ...
    def is_unsigned_integer(self) -> bool: ...
    def is_signed_integer(self) -> bool: ...
    def is_float(self) -> bool: ...
    def is_scalar(self) -> bool: ...
    def is_array(self) -> bool: ...
    def is_vector(self) -> bool: ...
    def is_struct(self) -> bool: ...
    # Size and properties
    def size_in_bytes(self) -> int: ...
    def num_elements(self) -> int: ...
    def struct_size_bytes(self) -> int: ...
    def struct_name(self) -> str: ...
    def short_name(self) -> str: ...
    # Related types
    def base_type(self) -> TypeInfo: ...
    def pointer_type(self) -> TypeInfo: ...
    # Field access
    def __getitem__(self, i: int) -> FieldEntry: ...
    def __getitem__(self, name: str) -> FieldEntry: ...
    # Operations
    def type_cast(self, src_value: ValueInfo) -> ValueInfo: ...
    def add(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def sub(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def mult(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def div(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def remainder(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def less_than(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def less_than_equal(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def greater_than(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def greater_than_equal(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def equal(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def not_equal(self, lhs: ValueInfo, rhs: ValueInfo) -> ValueInfo: ...
    def __eq__(self, other: TypeInfo) -> bool: ...
    # Static factory methods
    @staticmethod
    def null() -> TypeInfo: ...
    @staticmethod
    def mk_void() -> TypeInfo: ...
    @staticmethod
    def mk_bool() -> TypeInfo: ...
    @staticmethod
    def mk_int8() -> TypeInfo: ...
    @staticmethod
    def mk_int16() -> TypeInfo: ...
    @staticmethod
    def mk_int32() -> TypeInfo: ...
    @staticmethod
    def mk_int64() -> TypeInfo: ...
    @staticmethod
    def mk_uint8() -> TypeInfo: ...
    @staticmethod
    def mk_uint16() -> TypeInfo: ...
    @staticmethod
    def mk_uint32() -> TypeInfo: ...
    @staticmethod
    def mk_uint64() -> TypeInfo: ...
    @staticmethod
    def mk_float32() -> TypeInfo: ...
    @staticmethod
    def mk_float64() -> TypeInfo: ...
    @staticmethod
    def mk_array(element_type: TypeInfo, num_elements: int) -> TypeInfo: ...
    @staticmethod
    def mk_vector(element_type: TypeInfo, num_elements: int) -> TypeInfo: ...
    @staticmethod
    def mk_struct(name: str, element_list: List[MemberFieldEntry], is_packed: bool = True) -> TypeInfo: ...
    @staticmethod
    def mk_type_from_name(name: str) -> TypeInfo: ...

class LinkSymbolName:
    def __init__(self) -> None: ...
    def __init__(self, name: str) -> None: ...
    def __init__(self, ns: str, name: str) -> None: ...
    def short_name(self) -> str: ...
    def namespace_name(self) -> str: ...
    def full_name(self) -> str: ...
    def is_global(self) -> bool: ...
    def is_valid(self) -> bool: ...
    def equals_name(self, name: str) -> bool: ...
    def __eq__(self, other: LinkSymbolName) -> bool: ...
    @staticmethod
    def null() -> LinkSymbolName: ...

class LinkSymbol:
    def __init__(self) -> None: ...
    def __init__(self, name: LinkSymbolName, ctype: TypeInfo, type: SymbolType) -> None: ...
    def symbol_name(self) -> LinkSymbolName: ...
    def full_name(self) -> str: ...
    def is_valid(self) -> bool: ...
    def is_custom_struct(self) -> bool: ...
    def is_function(self) -> bool: ...
    def equals_name(self, name: str) -> bool: ...
    def add_arg(self, type: TypeInfo, name: str) -> None: ...
    def __eq__(self, other: LinkSymbol) -> bool: ...
    @staticmethod
    def null() -> LinkSymbol: ...

# Value classes
class TagInfo:
    def __init__(self) -> None: ...
    def __init__(self, value: str) -> None: ...
    def contains(self, v: str) -> bool: ...
    def add_entry(self, v: str) -> None: ...
    def set_union(self, other: TagInfo) -> TagInfo: ...

class ValueInfo:
    def __init__(self) -> None: ...
    # Queries
    def is_valid(self) -> bool: ...
    def type(self) -> TypeInfo: ...
    def tag_info(self) -> TagInfo: ...
    def has_tag(self, v: str) -> bool: ...
    def add_tag(self, v: str) -> None: ...
    def equals_type(self, other: ValueInfo) -> bool: ...
    def equals_type(self, type: TypeInfo) -> bool: ...
    # Type conversion
    def cast(self, target_type: TypeInfo) -> ValueInfo: ...
    # Arithmetic operations
    def add(self, v2: ValueInfo) -> ValueInfo: ...
    def sub(self, v2: ValueInfo) -> ValueInfo: ...
    def mult(self, v2: ValueInfo) -> ValueInfo: ...
    def div(self, v2: ValueInfo) -> ValueInfo: ...
    def remainder(self, v2: ValueInfo) -> ValueInfo: ...
    # Comparison operations
    def less_than(self, v2: ValueInfo) -> ValueInfo: ...
    def less_than_equal(self, v2: ValueInfo) -> ValueInfo: ...
    def greater_than(self, v2: ValueInfo) -> ValueInfo: ...
    def greater_than_equal(self, v2: ValueInfo) -> ValueInfo: ...
    def equal(self, v2: ValueInfo) -> ValueInfo: ...
    def not_equal(self, v2: ValueInfo) -> ValueInfo: ...
    # Conditional
    def cond(self, then_value: ValueInfo, else_value: ValueInfo) -> ValueInfo: ...
    # Python operators
    def __add__(self, v2: ValueInfo) -> ValueInfo: ...
    def __sub__(self, v2: ValueInfo) -> ValueInfo: ...
    def __mul__(self, v2: ValueInfo) -> ValueInfo: ...
    def __truediv__(self, v2: ValueInfo) -> ValueInfo: ...
    def __mod__(self, v2: ValueInfo) -> ValueInfo: ...
    def __lt__(self, v2: ValueInfo) -> ValueInfo: ...
    def __le__(self, v2: ValueInfo) -> ValueInfo: ...
    def __gt__(self, v2: ValueInfo) -> ValueInfo: ...
    def __ge__(self, v2: ValueInfo) -> ValueInfo: ...
    def __eq__(self, other: ValueInfo) -> bool: ...
    # Memory operations
    def store(self, value: ValueInfo) -> None: ...
    def load(self) -> ValueInfo: ...
    def entry(self, i: int) -> ValueInfo: ...
    def entry(self, i: ValueInfo) -> ValueInfo: ...
    def field(self, name: str) -> ValueInfo: ...
    # Vector operations
    def load_vector_entry(self, i: int) -> ValueInfo: ...
    def store_vector_entry(self, i: int, value: ValueInfo) -> ValueInfo: ...
    # Static factories
    @staticmethod
    def null() -> ValueInfo: ...
    @staticmethod
    def mk_pointer(type: TypeInfo) -> ValueInfo: ...
    @staticmethod
    def mk_array(type: TypeInfo) -> ValueInfo: ...
    @staticmethod
    def mk_struct(type: TypeInfo) -> ValueInfo: ...
    @staticmethod
    def calc_struct_size(type: TypeInfo) -> ValueInfo: ...
    @staticmethod
    def calc_struct_field_count(type: TypeInfo) -> ValueInfo: ...
    @staticmethod
    def calc_struct_field_offset(type: TypeInfo, idx: ValueInfo) -> ValueInfo: ...
    @staticmethod
    def from_bool(v: bool) -> ValueInfo: ...
    @staticmethod
    def from_int8(v: int) -> ValueInfo: ...
    @staticmethod
    def from_int16(v: int) -> ValueInfo: ...
    @staticmethod
    def from_int32(v: int) -> ValueInfo: ...
    @staticmethod
    def from_int64(v: int) -> ValueInfo: ...
    @staticmethod
    def from_uint8(v: int) -> ValueInfo: ...
    @staticmethod
    def from_uint16(v: int) -> ValueInfo: ...
    @staticmethod
    def from_uint32(v: int) -> ValueInfo: ...
    @staticmethod
    def from_uint64(v: int) -> ValueInfo: ...
    @staticmethod
    def from_float32(v: float) -> ValueInfo: ...
    @staticmethod
    def from_float64(v: float) -> ValueInfo: ...

# Function classes
class FnContext:
    def __init__(self) -> None: ...
    def __init__(self, type: TypeInfo) -> None: ...
    def type(self) -> TypeInfo: ...
    def value(self) -> ValueInfo: ...
    def check_type(self, value: ValueInfo) -> bool: ...
    def is_valid(self) -> bool: ...
    def is_init(self) -> bool: ...
    def __eq__(self, other: FnContext) -> bool: ...
    @staticmethod
    def null() -> FnContext: ...

class CodeSection:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def is_valid(self) -> bool: ...
    def is_open(self) -> bool: ...
    def is_commit(self) -> bool: ...
    def is_sealed(self) -> bool: ...
    def enter(self) -> None: ...
    def detach(self) -> CodeSection: ...
    def function(self) -> Function: ...
    def jump_to_section(self, dst: CodeSection) -> None: ...
    def conditional_jump(self, value: ValueInfo, then_dst: CodeSection, else_dst: CodeSection) -> None: ...
    def __eq__(self, other: CodeSection) -> bool: ...
    @staticmethod
    def null() -> CodeSection: ...

class CodeSectionContext:
    @staticmethod
    def push_var_context() -> None: ...
    @staticmethod
    def pop_var_context() -> None: ...
    @staticmethod
    def pop(name: str) -> ValueInfo: ...
    @staticmethod
    def push(name: str, v: ValueInfo) -> None: ...
    @staticmethod
    def mk_ptr(name: str, type: TypeInfo, default_value: ValueInfo) -> None: ...
    @staticmethod
    def function() -> Function: ...
    @staticmethod
    def set_return_value(value: ValueInfo) -> None: ...
    @staticmethod
    def mk_section(name: str) -> CodeSection: ...
    @staticmethod
    def jump_to_section(dst: CodeSection) -> None: ...
    @staticmethod
    def section_break(new_section_name: str) -> None: ...
    @staticmethod
    def current_section() -> CodeSection: ...
    @staticmethod
    def is_current_section(code: CodeSection) -> bool: ...
    @staticmethod
    def current_function() -> Function: ...
    @staticmethod
    def current_context() -> ValueInfo: ...
    @staticmethod
    def clean_sealed_context() -> int: ...
    @staticmethod
    def assert_no_context() -> None: ...

class Function:
    def __init__(self) -> None: ...
    def is_valid(self) -> bool: ...
    def parent_module(self) -> Module: ...
    def name(self) -> str: ...
    def is_external(self) -> bool: ...
    def return_type(self) -> TypeInfo: ...
    def call_fn(self, context: ValueInfo) -> ValueInfo: ...
    def declare_fn(self, src_mod: Module, dst_mod: Module) -> None: ...
    def mk_section(self, name: str) -> CodeSection: ...
    def verify(self) -> None: ...
    def remove_from_module(self) -> None: ...
    def write_to_ostream(self) -> None: ...
    def __eq__(self, other: Function) -> bool: ...
    @staticmethod
    def null() -> Function: ...

class FunctionBuilder:
    def __init__(self) -> None: ...
    def is_frozen(self) -> bool: ...
    def set_context(self, context: FnContext) -> FunctionBuilder: ...
    def set_name(self, name: str) -> FunctionBuilder: ...
    def set_module(self, mod: Module) -> FunctionBuilder: ...
    def mark_external(self) -> FunctionBuilder: ...
    def compile(self) -> Function: ...
    def __eq__(self, other: FunctionBuilder) -> bool: ...
    @staticmethod
    def null() -> FunctionBuilder: ...

# Module classes
class Module:
    def __init__(self) -> None: ...
    def is_init(self) -> bool: ...
    def name(self) -> str: ...
    def public_symbols(self) -> List[LinkSymbol]: ...
    def struct_type(self, name: str) -> TypeInfo: ...
    def exported_symbol_names(self) -> List[str]: ...
    def public_symbol_name(self, symbol: str) -> str: ...
    def contains(self, symbol: str) -> bool: ...
    def register_symbol(self, link_symbol: LinkSymbol) -> None: ...
    def init_standard(self) -> None: ...
    def get_function(self, name: str) -> Function: ...
    def add_struct_definition(self, struct_type: TypeInfo) -> None: ...
    def write_to_file(self) -> None: ...
    def write_llvm_output(self, suffix: str = "") -> None: ...
    def write_to_ostream(self) -> None: ...
    def __eq__(self, other: Module) -> bool: ...
    @staticmethod
    def null() -> Module: ...

class Cursor:
    def __init__(self) -> None: ...
    def __init__(self, name: str) -> None: ...
    def name(self) -> str: ...
    def main_module(self) -> Module: ...
    def gen_module(self) -> Module: ...
    def is_bind_called(self) -> bool: ...
    def bind(self) -> None: ...
    def cleanup(self) -> None: ...
    def __eq__(self, other: Cursor) -> bool: ...
    @staticmethod
    def null() -> Cursor: ...

# Control flow classes
class BranchSection:
    def is_open(self) -> bool: ...
    def is_sealed(self) -> bool: ...
    def enter(self) -> None: ...
    def exit(self) -> None: ...
    def define_branch(self, fn: Callable[[], None]) -> None: ...
    def code_section(self) -> CodeSection: ...

class IfElseCond:
    def __init__(self, name: str, value: ValueInfo) -> None: ...
    def is_sealed(self) -> bool: ...
    def then_branch(self, fn: Callable[[], None]) -> None: ...
    def else_branch(self, fn: Callable[[], None]) -> None: ...
    def get_then_branch(self) -> BranchSection: ...
    def get_else_branch(self) -> BranchSection: ...
    def bind(self) -> None: ...

# JIT classes
class RuntimeField:
    def __init__(self) -> None: ...
    def struct_def(self) -> RuntimeStruct: ...
    def idx(self) -> int: ...
    def offset(self) -> int: ...
    def name(self) -> str: ...
    def is_bool(self) -> bool: ...
    def is_struct_pointer(self) -> bool: ...
    def is_array_pointer(self) -> bool: ...
    def is_int8(self) -> bool: ...
    def is_int16(self) -> bool: ...
    def is_int32(self) -> bool: ...
    def is_int64(self) -> bool: ...
    def is_uint8(self) -> bool: ...
    def is_uint16(self) -> bool: ...
    def is_uint32(self) -> bool: ...
    def is_uint64(self) -> bool: ...
    def is_float32(self) -> bool: ...
    def is_float64(self) -> bool: ...
    def __eq__(self, other: RuntimeField) -> bool: ...
    @staticmethod
    def null() -> RuntimeField: ...
    @staticmethod
    def get_type(type: TypeInfo) -> RuntimeType: ...
    @staticmethod
    def get_raw_size(type: TypeInfo) -> int: ...

class RuntimeStruct:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def size_in_bytes(self) -> int: ...
    def num_fields(self) -> int: ...
    def field_names(self) -> List[str]: ...
    def mk_object(self) -> RuntimeObject: ...
    def __getitem__(self, name: str) -> RuntimeField: ...
    def __eq__(self, other: RuntimeStruct) -> bool: ...
    @staticmethod
    def null() -> RuntimeStruct: ...

class RuntimeArray:
    def __init__(self) -> None: ...
    def is_scalar(self) -> bool: ...
    def is_pointer(self) -> bool: ...
    def is_frozen(self) -> bool: ...
    def freeze(self) -> bool: ...
    def num_elements(self) -> int: ...
    def element_type(self) -> RuntimeType: ...
    def element_size(self) -> int: ...
    # Typed getters/setters
    def get_bool(self, i: int) -> bool: ...
    def get_int8(self, i: int) -> int: ...
    def get_int16(self, i: int) -> int: ...
    def get_int32(self, i: int) -> int: ...
    def get_int64(self, i: int) -> int: ...
    def get_uint8(self, i: int) -> int: ...
    def get_uint16(self, i: int) -> int: ...
    def get_uint32(self, i: int) -> int: ...
    def get_uint64(self, i: int) -> int: ...
    def get_float32(self, i: int) -> float: ...
    def get_float64(self, i: int) -> float: ...
    def set_bool(self, i: int, v: bool) -> None: ...
    def set_int8(self, i: int, v: int) -> None: ...
    def set_int16(self, i: int, v: int) -> None: ...
    def set_int32(self, i: int, v: int) -> None: ...
    def set_int64(self, i: int, v: int) -> None: ...
    def set_uint8(self, i: int, v: int) -> None: ...
    def set_uint16(self, i: int, v: int) -> None: ...
    def set_uint32(self, i: int, v: int) -> None: ...
    def set_uint64(self, i: int, v: int) -> None: ...
    def set_float32(self, i: int, v: float) -> None: ...
    def set_float64(self, i: int, v: float) -> None: ...
    def get_object(self, i: int) -> RuntimeObject: ...
    def set_object(self, i: int, v: RuntimeObject) -> None: ...
    def get_array(self, i: int) -> RuntimeArray: ...
    def set_array(self, i: int, v: RuntimeArray) -> None: ...
    def __eq__(self, other: RuntimeArray) -> bool: ...
    @staticmethod
    def null() -> RuntimeArray: ...
    @staticmethod
    def from(type: RuntimeType, size: int) -> RuntimeArray: ...

class RuntimeObject:
    def __init__(self) -> None: ...
    def is_frozen(self) -> bool: ...
    def freeze(self) -> bool: ...
    def null_fields(self) -> List[RuntimeField]: ...
    def is_instance_of(self, o: RuntimeStruct) -> bool: ...
    def struct_def(self) -> RuntimeStruct: ...
    # Typed getters/setters
    def get_bool(self, name: str) -> bool: ...
    def get_int8(self, name: str) -> int: ...
    def get_int16(self, name: str) -> int: ...
    def get_int32(self, name: str) -> int: ...
    def get_int64(self, name: str) -> int: ...
    def get_uint8(self, name: str) -> int: ...
    def get_uint16(self, name: str) -> int: ...
    def get_uint32(self, name: str) -> int: ...
    def get_uint64(self, name: str) -> int: ...
    def get_float32(self, name: str) -> float: ...
    def get_float64(self, name: str) -> float: ...
    def set_bool(self, name: str, v: bool) -> None: ...
    def set_int8(self, name: str, v: int) -> None: ...
    def set_int16(self, name: str, v: int) -> None: ...
    def set_int32(self, name: str, v: int) -> None: ...
    def set_int64(self, name: str, v: int) -> None: ...
    def set_uint8(self, name: str, v: int) -> None: ...
    def set_uint16(self, name: str, v: int) -> None: ...
    def set_uint32(self, name: str, v: int) -> None: ...
    def set_uint64(self, name: str, v: int) -> None: ...
    def set_float32(self, name: str, v: float) -> None: ...
    def set_float64(self, name: str, v: float) -> None: ...
    def get_object(self, name: str) -> RuntimeObject: ...
    def set_object(self, name: str, v: RuntimeObject) -> None: ...
    def get_array(self, name: str) -> RuntimeArray: ...
    def set_array(self, name: str, v: RuntimeArray) -> None: ...
    def __eq__(self, other: RuntimeObject) -> bool: ...
    @staticmethod
    def null() -> RuntimeObject: ...

class RuntimeEventFn:
    def __init__(self) -> None: ...
    def is_init(self) -> bool: ...
    def init(self) -> None: ...
    def on_event(self, o: RuntimeObject) -> int: ...
    def __eq__(self, other: RuntimeEventFn) -> bool: ...
    @staticmethod
    def null() -> RuntimeEventFn: ...

class RuntimeNamespace:
    def __init__(self) -> None: ...
    def name(self) -> str: ...
    def is_bind(self) -> bool: ...
    def is_global(self) -> bool: ...
    def bind(self) -> None: ...
    def struct_info(self, name: str) -> RuntimeStruct: ...
    def event_fn_info(self, name: str) -> RuntimeEventFn: ...
    def __eq__(self, other: RuntimeNamespace) -> bool: ...
    @staticmethod
    def null() -> RuntimeNamespace: ...

class JustInTimeRunner:
    def __init__(self) -> None: ...
    def bind(self) -> None: ...
    def is_bind(self) -> bool: ...
    def contains_symbol_definition(self, name: str) -> bool: ...
    def process_module_fn(self, fn: Function) -> bool: ...
    def add_module(self, cursor: Cursor) -> None: ...
    def get_namespace(self, name: str) -> RuntimeNamespace: ...
    def get_global_namespace(self) -> RuntimeNamespace: ...
    def __eq__(self, other: JustInTimeRunner) -> bool: ...
    @staticmethod
    def null() -> JustInTimeRunner: ...
